---
- name: Perform system upgrade
  apt:
    update_cache: yes
    upgrade: yes

- name: Install basic dependencies and packages
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
      - vim
      - nano
      - htop
      - iotop
      - iftop
      - net-tools
      - curl
      - wget
      - git
      - dirmngr
      - gpg
      - gawk
    state: present